SUBDIRS	= lib bin doc

CLEAN_FILES	+= config.h include/vcs_version. include/vmod_abi.h _.cache

TODO_INSTALL +=	top_install

TOPDIR = $(CURDIR)
include $(TOPDIR)/Makefile.inc.phk

.PHONY: top_install
top_install:	
	@for d in man doc etc bin lib libexec ; do \
		mkdir -p $(INSTALL_BASE)/$$d ; \
	done
