FROM archlinux:base-devel

RUN set -e; \
	pacman -Sy --noconfirm \
	       ca-certificates \
	       cpio \
	       git \
	       libedit \
	       libtool \
	       libunwind \
	       linux-headers \
	       pcre2 \
	       python-docutils \
	       python-sphinx \
	       tar
