FROM fedora-latest

RUN set -e; \
	dnf -y install \
	    automake \
	    git \
	    jemalloc-devel \
	    libedit-devel \
	    libtool \
	    libunwind-devel \
	    make \
	    pcre-devel \
	    python3 \
	    python3-sphinx
